# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run lint

    - name: Run the qualscan tool
      run: | 
        npm install qualscan -g
        qualscan --scripts

    - name: Run tests
      run: |
        npm run build
        npm run test
